version: '{build}'
skip_tags: true
image: Visual Studio 2022
build_script:
  - pwsh: ./Build.ps1
test: off
artifacts:
  - path: artifacts/Seq.*.nupkg
deploy:
  - provider: NuGet
    api_key:
      secure: o5zqGNFtcQztPNdUkaYLm+r2UvPz7LHW7dm4DYpcOAtmUXrVtcctPW6s5ARQ7XHD
    skip_symbols: true
    artifact: /Seq.App.*\.nupkg/
    on:
      branch: /^(main|dev)$/
  - provider: NuGet
    api_key:
      secure: UZN5e9OheyD5NnDWD+4DniYoATDUzO04NleRhvUwTRGSHzmX36P6s1SKf7lurrwe
    skip_symbols: true
    artifact: /Seq.Syntax.*\.nupkg/
    on:
      branch: /^(main|dev)$/
  - provider: NuGet
    api_key:
      secure: WsFbxKsRUnKsh8DJCYLdWkoqxhSFcQJhOGNghjKtyL3nVQ8z9mOWWQVbSR9YaH+8
    skip_symbols: true
    artifact: /Seq.Apps.Testing.*\.nupkg/
    on:
      branch: /^(main|dev)$/
  - provider: GitHub
    auth_token:
      secure: hX+cZmW+9BCXy7vyH8myWsYdtQHyzzil9K5yvjJv7dK9XmyrGYYDj/DPzMqsXSjo
    artifact: /Seq.*\.nupkg/
    tag: v$(appveyor_build_version)
    on:
      branch: main
